version: '3.5'
services:
  mr_mysql:
    image: 'mysql:latest'
    container_name: mr_mysql
    restart: always
    networks:
      net:
        ipv4_address: ${MYSQL_HOST}
    volumes:
      - './mysql/initdb/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
      - './mysql/data/:/var/lib/mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306

  mr_nginx:
    build: ./nginx
    container_name: mr_nginx
    restart: always
    networks:
      net:
        ipv4_address: ${NGINX_HOST}
    links:
      - mr_mysql
      - mr_php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
      - ${PROJECT_DEFAULT_PATH}:/var/www/service/

  mr_php:
    build:
      context: ./php
    tty: true
    container_name: mr_php
    restart: always
    links:
      - mr_mysql
    expose:
      - 9000
    volumes:
      - ${PROJECT_DEFAULT_PATH}:/var/www/service/
    networks:
      net:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
